### ISSUE TITLE
Command line version?

### ISSUE THREAD

**Issue by jaybird110127** [BrerDawg/ti_lpc#2]
Could there be a way to decode files or parts of files from the command line? I'm blind so don't use Linux GUI applications, but would love to play around with this, especially if it could be built under Windows.

**Comment by BrerDawg** [comment]
I've added a folder called 'cmd_line_vers', with some simple test code which should be quite portable. If you are able to build the code using your compiler's 'make'  while in this same folder you should get an app 'ti_lpc_cmd.exe'. If you run app it should generate a wav file with a simple tone. Let us know if you are able to compile and run it.

**Comment by jaybird110127** [comment]
I was able to compile this under Mingw, and it generated the tone as you described. For what it's worth, I couldn't compile it under Cygwin, it couldn't find share.h and my limited Googling failed to turn up a way to solve that problem. I think it also complained about a missing conio.h or somesuch. Anyway under Mingw the test code compiles and works fine.

**Comment by BrerDawg** [comment]
Have added code which will allow you to render audio from command line, see the 'ti_lpc_cmd_help.txt' for invocations examples.

**Comment by jaybird110127** [comment]
Thanks. Got it going, but possibly stupid question time. Where do I get the files such as tms5220.txt which the program seems to need?

**Comment by BrerDawg** [comment]
I noticed they were missing and put them in folder about an hour later.
